# SPDX-FileCopyrightText: 2016-2018 CERN.
# SPDX-License-Identifier: MIT

"""Create omicz_invenio tables."""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils
import invenio_db

# revision identifiers, used by Alembic.
revision = '1790158789'
down_revision = '1790158783'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('omics_metadata_version',
    sa.Column('bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=True),
    sa.Column('media_bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=True),
    sa.Column('deletion_status', sa.String(length=1), autoincrement=False, nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), autoincrement=False, nullable=True),
    sa.Column('version_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('index', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_omics_metadata_version')),
    if_not_exists=True,
    )
    op.create_index(op.f('ix_omics_metadata_version_end_transaction_id'), 'omics_metadata_version', ['end_transaction_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_omics_metadata_version_operation_type'), 'omics_metadata_version', ['operation_type'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_omics_metadata_version_transaction_id'), 'omics_metadata_version', ['transaction_id'], unique=False, if_not_exists=True)
    op.create_table('omics_parent_metadata',
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('workflow', sa.String(), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_omics_parent_metadata')),
    if_not_exists=True,
    )
    op.create_table('omics_draft_metadata',
    sa.Column('media_bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('deletion_status', sa.String(length=1), nullable=False),
    sa.Column('fork_version_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', invenio_db.shared.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['bucket_id'], ['files_bucket.id'], name=op.f('fk_omics_draft_metadata_bucket_id_files_bucket')),
    sa.ForeignKeyConstraint(['media_bucket_id'], ['files_bucket.id'], name=op.f('fk_omics_draft_metadata_media_bucket_id_files_bucket')),
    sa.ForeignKeyConstraint(['parent_id'], ['omics_parent_metadata.id'], name=op.f('fk_omics_draft_metadata_parent_id_omics_parent_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_omics_draft_metadata')),
    if_not_exists=True,
    )
    op.create_table('omics_metadata',
    sa.Column('bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('media_bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('deletion_status', sa.String(length=1), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['bucket_id'], ['files_bucket.id'], name=op.f('fk_omics_metadata_bucket_id_files_bucket')),
    sa.ForeignKeyConstraint(['media_bucket_id'], ['files_bucket.id'], name=op.f('fk_omics_metadata_media_bucket_id_files_bucket')),
    sa.ForeignKeyConstraint(['parent_id'], ['omics_parent_metadata.id'], name=op.f('fk_omics_metadata_parent_id_omics_parent_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_omics_metadata')),
    if_not_exists=True,
    )
    op.create_table('omics_draft_files',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('key', sa.Text().with_variant(mysql.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('object_version_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['object_version_id'], ['files_object.version_id'], name=op.f('fk_omics_draft_files_object_version_id_files_object'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['omics_draft_metadata.id'], name=op.f('fk_omics_draft_files_record_id_omics_draft_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_omics_draft_files')),
    if_not_exists=True,
    )
    op.create_index(op.f('ix_omics_draft_files_object_version_id'), 'omics_draft_files', ['object_version_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_omics_draft_files_record_id'), 'omics_draft_files', ['record_id'], unique=False, if_not_exists=True)
    op.create_index('uidx_omics_draft_files_record_id_key', 'omics_draft_files', ['record_id', 'key'], unique=True, if_not_exists=True)
    op.create_table('omics_draft_media_files',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('key', sa.Text().with_variant(mysql.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('object_version_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['object_version_id'], ['files_object.version_id'], name=op.f('fk_omics_draft_media_files_object_version_id_files_object'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['omics_draft_metadata.id'], name=op.f('fk_omics_draft_media_files_record_id_omics_draft_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_omics_draft_media_files')),
    if_not_exists=True,
    )
    op.create_index(op.f('ix_omics_draft_media_files_object_version_id'), 'omics_draft_media_files', ['object_version_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_omics_draft_media_files_record_id'), 'omics_draft_media_files', ['record_id'], unique=False, if_not_exists=True)
    op.create_index('uidx_omics_draft_media_files_record_id_key', 'omics_draft_media_files', ['record_id', 'key'], unique=True, if_not_exists=True)
    op.create_table('omics_files',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('key', sa.Text().with_variant(mysql.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('object_version_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['object_version_id'], ['files_object.version_id'], name=op.f('fk_omics_files_object_version_id_files_object'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['omics_metadata.id'], name=op.f('fk_omics_files_record_id_omics_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_omics_files')),
    if_not_exists=True,
    )
    op.create_index(op.f('ix_omics_files_object_version_id'), 'omics_files', ['object_version_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_omics_files_record_id'), 'omics_files', ['record_id'], unique=False, if_not_exists=True)
    op.create_index('uidx_omics_files_record_id_key', 'omics_files', ['record_id', 'key'], unique=True, if_not_exists=True)
    op.create_table('omics_media_files',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('key', sa.Text().with_variant(mysql.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('object_version_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['object_version_id'], ['files_object.version_id'], name=op.f('fk_omics_media_files_object_version_id_files_object'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['omics_metadata.id'], name=op.f('fk_omics_media_files_record_id_omics_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_omics_media_files')),
    if_not_exists=True,
    )
    op.create_index(op.f('ix_omics_media_files_object_version_id'), 'omics_media_files', ['object_version_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_omics_media_files_record_id'), 'omics_media_files', ['record_id'], unique=False, if_not_exists=True)
    op.create_index('uidx_omics_media_files_record_id_key', 'omics_media_files', ['record_id', 'key'], unique=True, if_not_exists=True)
    op.create_table('omics_parent_record_state',
    sa.Column('latest_index', sa.Integer(), nullable=True),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('latest_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('next_draft_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['latest_id'], ['omics_metadata.id'], name=op.f('fk_omics_parent_record_state_latest_id_omics_metadata')),
    sa.ForeignKeyConstraint(['next_draft_id'], ['omics_draft_metadata.id'], name=op.f('fk_omics_parent_record_state_next_draft_id_omics_draft_metadata')),
    sa.ForeignKeyConstraint(['parent_id'], ['omics_parent_metadata.id'], name=op.f('fk_omics_parent_record_state_parent_id_omics_parent_metadata'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_id', name=op.f('pk_omics_parent_record_state')),
    if_not_exists=True,
    )
    op.create_table('omics_parents_community',
    sa.Column('community_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('request_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities_metadata.id'], name=op.f('fk_omics_parents_community_community_id_communities_metadata'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['record_id'], ['omics_parent_metadata.id'], name=op.f('fk_omics_parents_community_record_id_omics_parent_metadata'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['request_metadata.id'], name=op.f('fk_omics_parents_community_request_id_request_metadata'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('community_id', 'record_id', name=op.f('pk_omics_parents_community')),
    if_not_exists=True,
    )
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('omics_parents_community', if_exists=True)
    op.drop_table('omics_parent_record_state', if_exists=True)
    op.drop_index('uidx_omics_media_files_record_id_key', table_name='omics_media_files', if_exists=True)
    op.drop_index(op.f('ix_omics_media_files_record_id'), table_name='omics_media_files', if_exists=True)
    op.drop_index(op.f('ix_omics_media_files_object_version_id'), table_name='omics_media_files', if_exists=True)
    op.drop_table('omics_media_files', if_exists=True)
    op.drop_index('uidx_omics_files_record_id_key', table_name='omics_files', if_exists=True)
    op.drop_index(op.f('ix_omics_files_record_id'), table_name='omics_files', if_exists=True)
    op.drop_index(op.f('ix_omics_files_object_version_id'), table_name='omics_files', if_exists=True)
    op.drop_table('omics_files', if_exists=True)
    op.drop_index('uidx_omics_draft_media_files_record_id_key', table_name='omics_draft_media_files', if_exists=True)
    op.drop_index(op.f('ix_omics_draft_media_files_record_id'), table_name='omics_draft_media_files', if_exists=True)
    op.drop_index(op.f('ix_omics_draft_media_files_object_version_id'), table_name='omics_draft_media_files', if_exists=True)
    op.drop_table('omics_draft_media_files', if_exists=True)
    op.drop_index('uidx_omics_draft_files_record_id_key', table_name='omics_draft_files', if_exists=True)
    op.drop_index(op.f('ix_omics_draft_files_record_id'), table_name='omics_draft_files', if_exists=True)
    op.drop_index(op.f('ix_omics_draft_files_object_version_id'), table_name='omics_draft_files', if_exists=True)
    op.drop_table('omics_draft_files', if_exists=True)
    op.drop_table('omics_metadata', if_exists=True)
    op.drop_table('omics_draft_metadata', if_exists=True)
    op.drop_table('omics_parent_metadata', if_exists=True)
    op.drop_index(op.f('ix_omics_metadata_version_transaction_id'), table_name='omics_metadata_version', if_exists=True)
    op.drop_index(op.f('ix_omics_metadata_version_operation_type'), table_name='omics_metadata_version', if_exists=True)
    op.drop_index(op.f('ix_omics_metadata_version_end_transaction_id'), table_name='omics_metadata_version', if_exists=True)
    op.drop_table('omics_metadata_version', if_exists=True)
    # ### end Alembic commands ###
